/*
 * File:           C:\Users\Sanya\Desktop\1701\ADAU1701_IC_1_PARAM.h
 *
 * Created:        Tuesday, March 30, 2021 9:12:38 PM
 * Description:    ADAU1701:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2021 Analog Devices, Inc. All rights reserved.
 */
#ifndef __ADAU1701_IC_1_PARAM_H__
#define __ADAU1701_IC_1_PARAM_H__


/* Module Tone1 - Sine Tone*/
#define MOD_TONE1_COUNT                                3
#define MOD_TONE1_DEVICE                               "IC1"
#define MOD_STATIC_TONE1_ALG0_MASK_ADDR                0
#define MOD_STATIC_TONE1_ALG0_MASK_FIXPT               0x000000FF
#define MOD_STATIC_TONE1_ALG0_MASK_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_TONE1_ALG0_MASK_TYPE                SIGMASTUDIOTYPE_INTEGER
#define MOD_TONE1_ALG0_INCREMENT_ADDR                  1
#define MOD_TONE1_ALG0_INCREMENT_FIXPT                 0x000FC805
#define MOD_TONE1_ALG0_INCREMENT_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.123291666666667)
#define MOD_TONE1_ALG0_INCREMENT_TYPE                  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TONE1_ALG0_ON_ADDR                         2
#define MOD_TONE1_ALG0_ON_FIXPT                        0x00000000
#define MOD_TONE1_ALG0_ON_VALUE                        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_TONE1_ALG0_ON_TYPE                         SIGMASTUDIOTYPE_FIXPOINT

/* Module M Mixer1 - Multiple Control Mixer*/
#define MOD_MMIXER1_COUNT                              5
#define MOD_MMIXER1_DEVICE                             "IC1"
#define MOD_MMIXER1_ALG0_STAGE0_VOLUME_ADDR            3
#define MOD_MMIXER1_ALG0_STAGE0_VOLUME_FIXPT           0x008F9E4C
#define MOD_MMIXER1_ALG0_STAGE0_VOLUME_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.12201845430196)
#define MOD_MMIXER1_ALG0_STAGE0_VOLUME_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MMIXER1_ALG0_STAGE1_VOLUME_ADDR            4
#define MOD_MMIXER1_ALG0_STAGE1_VOLUME_FIXPT           0x00800000
#define MOD_MMIXER1_ALG0_STAGE1_VOLUME_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MMIXER1_ALG0_STAGE1_VOLUME_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MMIXER1_ALG0_STAGE2_VOLUME_ADDR            5
#define MOD_MMIXER1_ALG0_STAGE2_VOLUME_FIXPT           0x008F9E4C
#define MOD_MMIXER1_ALG0_STAGE2_VOLUME_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.12201845430196)
#define MOD_MMIXER1_ALG0_STAGE2_VOLUME_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MMIXER1_ALG0_STAGE3_VOLUME_ADDR            6
#define MOD_MMIXER1_ALG0_STAGE3_VOLUME_FIXPT           0x00721482
#define MOD_MMIXER1_ALG0_STAGE3_VOLUME_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.891250938133746)
#define MOD_MMIXER1_ALG0_STAGE3_VOLUME_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MMIXER1_ALG0_STAGE4_VOLUME_ADDR            7
#define MOD_MMIXER1_ALG0_STAGE4_VOLUME_FIXPT           0x00040C37
#define MOD_MMIXER1_ALG0_STAGE4_VOLUME_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0316227766016838)
#define MOD_MMIXER1_ALG0_STAGE4_VOLUME_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module Single 1 - Single Volume*/
#define MOD_SINGLE1_COUNT                              1
#define MOD_SINGLE1_DEVICE                             "IC1"
#define MOD_SINGLE1_GAIN1940ALGNS1_ADDR                8
#define MOD_SINGLE1_GAIN1940ALGNS1_FIXPT               0x00800000
#define MOD_SINGLE1_GAIN1940ALGNS1_VALUE               SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SINGLE1_GAIN1940ALGNS1_TYPE                SIGMASTUDIOTYPE_FIXPOINT

/* Module 1 X RTA1 - Single Level Detector*/
#define MOD_1XRTA1_COUNT                               5
#define MOD_1XRTA1_DEVICE                              "IC1"
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1TCONST_ADDR 9
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1TCONST_FIXPT 0x00004EB0
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00240140490349172)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1HOLD_ADDR   10
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1HOLD_FIXPT  0x000001E0
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1HOLD_VALUE  SIGMASTUDIOTYPE_INTEGER_CONVERT(480)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1HOLD_TYPE   SIGMASTUDIOTYPE_INTEGER
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1DECAY_ADDR  11
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1DECAY_FIXPT 0x0000071C
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000217013888888889)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1DECAY_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1_ADDR       2074
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1_VALUES     SIGMASTUDIOTYPE_SPECIAL(0x0152)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDET1_TYPE       SIGMASTUDIOTYPE_SPECIAL
#define MOD_1XRTA1_ALG0_ADDR                           2074
#define MOD_1XRTA1_ALG0_VALUE                          SIGMASTUDIOTYPE_10_14_CONVERT(0)
#define MOD_1XRTA1_ALG0_TYPE                           SIGMASTUDIOTYPE_10_14

#endif
