/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
library;
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData ac_unit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_7 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_auto = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData system_update_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compare_arrows = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insert_chart = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_input_component = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start_alt = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end_alt = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circle = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData params = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_settings_new = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_lock_rotation = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_rotation = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_input_hdmi = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData developer_board = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_align_left = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equalizer = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_icon = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_problem = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_backward = IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xf049, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward = IconData(0xf04a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_1 = IconData(0xf04b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_1 = IconData(0xf04c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_1 = IconData(0xf04d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xf04e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation_triangle = IconData(0xf071, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug = IconData(0xf1e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usb = IconData(0xf287, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microchip = IconData(0xf2db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal = IconData(0xf31a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xf325, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmute = IconData(0xf326, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_high = IconData(0xf769, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_low = IconData(0xf76b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
