// ignore_for_file: public_member_api_docs, sort_constructors_first
class Action {
  final String action;
  final String description;
  const Action({
    required this.action,
    required this.description,
  });
}

const Map<int, Action> btnAction = {
  0: Action(
      action: "Не назаначено",
      description: "Для настройки кнопки выберите необходимые параметры"),
  1: Action(action: "Перезагрузка платформы", description: ""),

  10: Action(action: "Камера заднего хода", description: ""),
  //11 Триггеры
  11: Action(action: "Управление триггером 1", description: ""),
  12: Action(action: "Управление триггером 2", description: ""),
  13: Action(action: "Управление триггером 3", description: ""),
  //18 Мультируль
  17: Action(action: "Мультируль настраиваемый", description: ""),
  18: Action(action: "Мултируль выбор", description: ""),
  19: Action(action: "Мультируль клик вперёд", description: ""),
  20: Action(action: "Мультируль клик назад", description: ""),
  21: Action(action: "Мультируль удерживаение вперёд", description: ""),
  22: Action(action: "Мультируль удерживаение назад", description: ""),
  23: Action(action: "Увеличить громкость", description: ""),
  24: Action(action: "Уменьшить громкость", description: ""),
  25: Action(action: "Муте", description: ""),
  26: Action(action: "ATT", description: ""),
  //HID клавиатура
  42: Action(action: "HID Play/Pause", description: ""),
  43: Action(action: "HID Play", description: ""),
  44: Action(action: "HID Pause", description: ""),
  45: Action(action: "HID Stop", description: ""),
  46: Action(action: "HID Mute", description: ""),
  47: Action(action: "HID next", description: ""),
  48: Action(action: "HID previus", description: ""),
  49: Action(action: "HID forward", description: ""),
  50: Action(action: "HID rewind", description: ""),
  51: Action(action: "HID Alt Tab", description: ""),
  52: Action(action: "HID Sleep", description: ""),
  53: Action(action: "HID PowerDown", description: ""),
  54: Action(action: "HID WakeUP", description: ""),
  //DSP переключение источника звука
  60: Action(action: "Переключить источник звук +", description: ""),
  61: Action(action: "Переключить источник звук -", description: ""),
  62: Action(action: "Выбрать источник звука USB Audio", description: ""),
  63: Action(action: "Выбрать источник звука Bluetooth", description: ""),
  64: Action(action: "Выбрать источник звука Aux", description: ""),
  65: Action(action: "Выбрать источник звука FM Radio", description: ""),
  66: Action(action: "Выбрать источник звука Spdif", description: ""),
  67: Action(action: "Выбрать источник звука Microphone", description: ""),
  //DSP включение отключение источника звука
  75: Action(action: "Включить/отключить USB Audio", description: ""),
  76: Action(action: "Включить/отключить Bluetooth", description: ""),
  77: Action(action: "Включить/отключить Aux", description: ""),
  78: Action(action: "Включить/отключить FM Radio", description: ""),
  79: Action(action: "Включить/отключить Spdif", description: ""),
  80: Action(action: "Включить/отключить Microphone", description: ""),
  //Меню дисплея
  100: Action(action: "Меню дисплея Налево", description: ""),
  101: Action(action: "Меню дисплея Вверх", description: ""),
  102: Action(action: "Меню дисплея Вниз", description: ""),
  103: Action(action: "Меню дисплея Направо", description: ""),
  104: Action(action: "Меню дисплея Выбор", description: ""),
  105: Action(action: "Меню дисплея Ничего", description: ""),
  106: Action(action: "Меню дисплея Назад", description: ""),
  107: Action(action: "Меню дисплея Открыть меню", description: ""),
  108: Action(action: "Меню дисплея Закрыть меню", description: ""),
  //Управление громкостью источников звука
  130: Action(action: "Громкость + USB Audio", description: ""),
  131: Action(action: "Громкость - USB Audio", description: ""),
  132: Action(action: "Громкость + Bluetooth", description: ""),
  133: Action(action: "Громкость - Bluetooth", description: ""),
  134: Action(action: "Громкость + Aux", description: ""),
  135: Action(action: "Громкость - Aux", description: ""),
  136: Action(action: "Громкость + FM Radio", description: ""),
  137: Action(action: "Громкость - FM Radio", description: ""),
  138: Action(action: "Громкость + SPDIF", description: ""),
  139: Action(action: "Громкость - SPDIF", description: ""),
  140: Action(action: "Громкость + Микрофон", description: ""),
  141: Action(action: "Громкость - Микрофон", description: ""),
  142: Action(action: "Громкость + Beep", description: ""),
  143: Action(action: "Громкость - Beep", description: ""),
  //Управление громкостью группой аудиовыходов
  150: Action(action: "Громкость + Группа каналов 1 и 2", description: ""),
  151: Action(action: "Громкость - Группа каналов 1 и 2", description: ""),
  152: Action(action: "Громкость + Группа каналов 3 и 4", description: ""),
  153: Action(action: "Громкость - Группа каналов 3 и 4", description: ""),
  154: Action(action: "Громкость + Группа каналов 5 и 6", description: ""),
  155: Action(action: "Громкость - Группа каналов 5 и 6", description: ""),
  156: Action(action: "Громкость + Группа каналов 7 и 8", description: ""),
  157: Action(action: "Громкость - Группа каналов 7 и 8", description: ""),
  158: Action(action: "Громкость + Группа каналов 9 и 10", description: ""),
  159: Action(action: "Громкость - Группа каналов 9 и 10", description: ""),
  160: Action(action: "Громкость + Группа каналов 11 и 12", description: ""),
  161: Action(action: "Громкость - Группа каналов 11 и 12", description: ""),
  162: Action(action: "Громкость + Группа SPDIF L и R", description: ""),
  163: Action(action: "Громкость - Группа SPDIF L и R", description: ""),
  //Управление громкостью аудиовыходов
  170: Action(action: "Громкость + Канал 1", description: ""),
  171: Action(action: "Громкость - Канал 1", description: ""),
  172: Action(action: "Громкость + Канал 2", description: ""),
  173: Action(action: "Громкость - Канал 2", description: ""),
  174: Action(action: "Громкость + Канал 3", description: ""),
  175: Action(action: "Громкость - Канал 3", description: ""),
  176: Action(action: "Громкость + Канал 4", description: ""),
  177: Action(action: "Громкость - Канал 4", description: ""),
  178: Action(action: "Громкость + Канал 5", description: ""),
  179: Action(action: "Громкость - Канал 5", description: ""),
  180: Action(action: "Громкость + Канал 6", description: ""),
  181: Action(action: "Громкость - Канал 6", description: ""),
  182: Action(action: "Громкость + Канал 7", description: ""),
  183: Action(action: "Громкость - Канал 7", description: ""),
  184: Action(action: "Громкость + Канал 8", description: ""),
  185: Action(action: "Громкость - Канал 8", description: ""),
  186: Action(action: "Громкость + Канал 9", description: ""),
  187: Action(action: "Громкость - Канал 9", description: ""),
  188: Action(action: "Громкость + Канал 10", description: ""),
  189: Action(action: "Громкость - Канал 10", description: ""),
  190: Action(action: "Громкость + Канал 11", description: ""),
  191: Action(action: "Громкость - Канал 11", description: ""),
  192: Action(action: "Громкость + Канал 12", description: ""),
  193: Action(action: "Громкость - Канал 12", description: ""),
  194: Action(action: "Громкость + SPDIF L", description: ""),
  195: Action(action: "Громкость - SPDIF L ", description: ""),
  196: Action(action: "Громкость + SPDIF R ", description: ""),
  197: Action(action: "Громкость - SPDIF R ", description: ""),
  //Переключение пресетов DSP процессора
  230: Action(action: "DSP пресет слудующий", description: ""),
  231: Action(action: "DSP пресет предыдущий", description: ""),
  232: Action(action: "DSP пресет 1", description: ""),
  233: Action(action: "DSP пресет 2", description: ""),
  234: Action(action: "DSP пресет 3", description: ""),
  //Переключение пресетов FM радио
  290: Action(action: "FM пресет слудующий", description: ""),
  291: Action(action: "FM пресет предыдущий", description: ""),
  292: Action(action: "FM пресет 1", description: ""),
  293: Action(action: "FM пресет 2", description: ""),
  294: Action(action: "FM пресет 3", description: ""),
  295: Action(action: "FM пресет 4", description: ""),
  296: Action(action: "FM пресет 5", description: ""),
  297: Action(action: "FM пресет 6", description: ""),
  298: Action(action: "FM пресет 7", description: ""),
  299: Action(action: "FM пресет 8", description: ""),
  300: Action(action: "FM пресет 9", description: ""),
  301: Action(action: "FM пресет 10", description: ""),
  //Управляемые функции
  331: Action(action: "Мультируль произвольный", description: ""),
};
